### ISSUE TITLE
--mean=(104.00698793, 116.66876762, 122.67891434): Expect argument to be a string, int, or float, found <type 'tuple'>

### ISSUE THREAD

**Issue by Aa456789** [SketchyScene/SketchyScene#12]
tf.app.flags.DEFINE_float(
    'mean', (104.00698793, 116.66876762, 122.67891434), 'The mean array')

**Comment by MarkMoHR** [comment]
Hi @Aa456789 ,

Maybe this is caused by the version of TensorFlow and Python. It works on Python3.5 and TensorFlow1.4.0. 

Alternatively, there is also an easy way to deal with this problem: just uncomment these two lines in `configs.py` and set [Line27](https://github.com/SketchyScene/SketchyScene/blob/master/Semantic_Segmentation/segment_main.py#L27) in `segment_main.py` to

```
mu = (104.00698793, 116.66876762, 122.67891434)
```
