### ISSUE TITLE
Why use duplicate color?

### ISSUE THREAD

**Issue by drcege** [SketchyScene/SketchyScene#20]
Color `[0,62,53]` is reused 8 times in the colorMap file. 

Is this a bug? If they appear together, the semantic annotation is indistinguishable.

**Comment by ruofeidu** [comment]
Hi Ce,

Sorry for the late reply and thank you for your feedback! This is an intended design choice. I reviewed http://go.duruofei.com/skenew/public/js/input/category.js?19, these classes (bicycle, bottle, bucket, cup, dinnerware, sofa, umbrella) are actually merged into the "others" category, because these are categories with fewer searched components. I think only sketches with color strokes are impacted, while the instance-level sketches are precisely recorded in digitalized data.

I sincerely agree that a better design will be using separate colors and merging these during the data preprocessing phase. If user drew strokes of `bicycle` and `bottle` in the same sketch, it may lead to confusion. I don't think it occurs in the dataset. Please report if you find a case with confusing strokes. 

Cheers,
Ruofei
